tracing/runtime: Fix extraction of struct g
As explained in the previous patch we extract struct g from Go runtime
but there is a problem with that indicated by our g.startpc yielding
wrong values:

    --- FAIL: TestGetG (0.01s)
        runtime_g_test.go:30: XFAIL: currently fails wrt g.startpc
        runtime_g_test.go:49: goroutine 7: have goid=7  startpc=0x0 ();  want goid=7  startpc=0x53ae40 (lab.nexedi.com/kirr/go123/tracing/internal/xruntime.ginfo)
        runtime_g_test.go:49: goroutine 24: have goid=24  startpc=0x0 ();  want goid=24  startpc=0x53ae40 (lab.nexedi.com/kirr/go123/tracing/internal/xruntime.ginfo)
        runtime_g_test.go:49: goroutine 9: have goid=9  startpc=0x0 ();  want goid=9  startpc=0x53ae40 (lab.nexedi.com/kirr/go123/tracing/internal/xruntime.ginfo)
        runtime_g_test.go:49: goroutine 10: have goid=10  startpc=0x0 ();  want goid=10  startpc=0x53ae40 (lab.nexedi.com/kirr/go123/tracing/internal/xruntime.ginfo)
        runtime_g_test.go:49: goroutine 18: have goid=18  startpc=0x0 ();  want goid=18  startpc=0x53ae40 (lab.nexedi.com/kirr/go123/tracing/internal/xruntime.ginfo)
        runtime_g_test.go:49: goroutine 8: have goid=8  startpc=0x0 ();  want goid=8  startpc=0x53ae40 (lab.nexedi.com/kirr/go123/tracing/internal/xruntime.ginfo)
        runtime_g_test.go:49: goroutine 19: have goid=19  startpc=0x0 ();  want goid=19  startpc=0x53ae40 (lab.nexedi.com/kirr/go123/tracing/internal/xruntime.ginfo)
        runtime_g_test.go:49: goroutine 21: have goid=21  startpc=0x0 ();  want goid=21  startpc=0x53ae40 (lab.nexedi.com/kirr/go123/tracing/internal/xruntime.ginfo)
        runtime_g_test.go:49: goroutine 22: have goid=22  startpc=0x0 ();  want goid=22  startpc=0x53ae40 (lab.nexedi.com/kirr/go123/tracing/internal/xruntime.ginfo)

This problem turned out to happen because in our version of the struct
.startpc had different offset than in runtime.g version because starting
from Go1.20 g.partkingOnChan was changed from uint8 to
runtime/internal/atomic.Bool, but in 0399d7ad (tracing/runtime: Add
support for Go1.20) I incorrectly replaced that with just sync/atomic.Bool .

It was not correct to do because it turns out those two types have
different sizes: sync/atomic.Bool is uint32, while
runtime/internal/atomic.Bool is uint8:

    https://github.com/golang/go/blob/go1.20.14-0-g90a870f1dc4/src/sync/atomic/type.go#L9-L14
    https://github.com/golang/go/blob/go1.20.14-0-g90a870f1dc4/src/runtime/internal/atomic/types.go#L156-L162

-> Fix that by extracting definition of runtime/internal/atomic.Bool +
friends directly instead of making the assumption.

Now TestGetG passes ok on all go versions. And since g.startpc is
relatively close to the end of struct g we can be practically sure that all
g fields, that precede .startpc, are extracted correctly:

    https://github.com/golang/go/blob/go1.26.0-0-gd90b98e6532/src/runtime/runtime2.go#L473-L561

which practically means that TestGetG is doing its job ok.