tracing/runtime: Add test for getg + retrieved g struct
Since c0f14991 (tracing: Part 3 - Silence race-detector about
probe.Detach) we are extracting the definition of `struct g` from Go
runtime and also have custom assembly getg function to retrieve g
pointer of current goroutine. It used to work in manual tests. However
there was no automatic testing that it was correct.

Add simple test that verifies that getg returns sensible result via
checking returned g's fields against public information about that
goroutine that we can retrieve via another ways without hacks. That
currently comes with g.goid, retrieved via runtime.Stack, and g.startpc,
because if we start a goroutine ourselves we know what we start.

And added test shows that though getg and g.goid seem to be correct, we
have a problem with g.startpc:

    --- FAIL: TestGetG (0.01s)
        runtime_g_test.go:30: XFAIL: currently fails wrt g.startpc
        runtime_g_test.go:49: goroutine 7: have goid=7  startpc=0x0 ();  want goid=7  startpc=0x53ae40 (lab.nexedi.com/kirr/go123/tracing/internal/xruntime.ginfo)
        runtime_g_test.go:49: goroutine 24: have goid=24  startpc=0x0 ();  want goid=24  startpc=0x53ae40 (lab.nexedi.com/kirr/go123/tracing/internal/xruntime.ginfo)
        runtime_g_test.go:49: goroutine 9: have goid=9  startpc=0x0 ();  want goid=9  startpc=0x53ae40 (lab.nexedi.com/kirr/go123/tracing/internal/xruntime.ginfo)
        runtime_g_test.go:49: goroutine 10: have goid=10  startpc=0x0 ();  want goid=10  startpc=0x53ae40 (lab.nexedi.com/kirr/go123/tracing/internal/xruntime.ginfo)
        runtime_g_test.go:49: goroutine 18: have goid=18  startpc=0x0 ();  want goid=18  startpc=0x53ae40 (lab.nexedi.com/kirr/go123/tracing/internal/xruntime.ginfo)
        runtime_g_test.go:49: goroutine 8: have goid=8  startpc=0x0 ();  want goid=8  startpc=0x53ae40 (lab.nexedi.com/kirr/go123/tracing/internal/xruntime.ginfo)
        runtime_g_test.go:49: goroutine 19: have goid=19  startpc=0x0 ();  want goid=19  startpc=0x53ae40 (lab.nexedi.com/kirr/go123/tracing/internal/xruntime.ginfo)
        runtime_g_test.go:49: goroutine 21: have goid=21  startpc=0x0 ();  want goid=21  startpc=0x53ae40 (lab.nexedi.com/kirr/go123/tracing/internal/xruntime.ginfo)
        runtime_g_test.go:49: goroutine 22: have goid=22  startpc=0x0 ();  want goid=22  startpc=0x53ae40 (lab.nexedi.com/kirr/go123/tracing/internal/xruntime.ginfo)

We will fix this problem in the next patch.